#!/usr/local/bin/node

const exec = require('child_process').exec
const allScripts = require('./allScripts')  // 所以支持的脚本选项

const PDIR = '/Users/morika/Desktop/myShell/'

const OPTION = process.argv[2]
const ARGV = process.argv[3] || '' 

// check command right
if (!allScripts[OPTION]) {
    console.log('对不起，本脚本不支持该选项!')
    process.exit(1)
}

exec('node ' + PDIR + allScripts[OPTION] + ' ' + ARGV, (err, stdout, stderr) => {
    if (err) return console.log(err, allScripts[OPTION] + ' 命令加载错误')
    // 打印子进程的输出
    console.log(stdout)
})